<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Galka2012" name="galka.streletskaya.myProject.TestSuite" tests="7" failures="0" timestamp="8 Oct 2015 08:40:15 GMT" time="69.075" errors="7">
  <testcase name="Test_01" time="8.728" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Only one &#039;@&#039; symbol is allowed!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;None of the special characters in local part are allowed outside quotation marks!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Quoted strings must be dot separated or the only element making up the local-part!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Double dot is not allowed before &#039;@&#039; symbol!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Double dot is not allowed after &#039;@&#039; symbol!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Email address should match current format: username@domain.&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Only one '@' symbol is allowed!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'None of the special characters in local part are allowed outside quotation marks!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Quoted strings must be dot separated or the only element making up the local-part!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Double dot is not allowed before '@' symbol!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Double dot is not allowed after '@' symbol!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Email address should match current format: username@domain.', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
  <testcase name="Test_01" time="17.803" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
  <testcase name="Test_01" time="8.375" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Only one &#039;@&#039; symbol is allowed!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;None of the special characters in local part are allowed outside quotation marks!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Only one '@' symbol is allowed!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'None of the special characters in local part are allowed outside quotation marks!', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
  <testcase name="Test_01" time="8.344" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Only one &#039;@&#039; symbol is allowed!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;None of the special characters in local part are allowed outside quotation marks!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Quoted strings must be dot separated or the only element making up the local-part!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Double dot is not allowed before &#039;@&#039; symbol!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Double dot is not allowed after &#039;@&#039; symbol!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Only one '@' symbol is allowed!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'None of the special characters in local part are allowed outside quotation marks!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Quoted strings must be dot separated or the only element making up the local-part!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Double dot is not allowed before '@' symbol!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Double dot is not allowed after '@' symbol!', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
  <testcase name="Test_01" time="8.639" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Only one &#039;@&#039; symbol is allowed!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;None of the special characters in local part are allowed outside quotation marks!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Quoted strings must be dot separated or the only element making up the local-part!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Only one '@' symbol is allowed!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'None of the special characters in local part are allowed outside quotation marks!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Quoted strings must be dot separated or the only element making up the local-part!', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
  <testcase name="Test_01" time="8.692" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Only one &#039;@&#039; symbol is allowed!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Only one '@' symbol is allowed!', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
  <testcase name="Test_01" time="8.494" classname="galka.streletskaya.myProject.TestSuite">
    <error type="java.lang.Exception" message="Assertion Error has occured:  
[Assertion Error has occured:Expected error message: &#039;A &#039;@&#039; character must separate the local and domain parts!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Only one &#039;@&#039; symbol is allowed!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;None of the special characters in local part are allowed outside quotation marks!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Quoted strings must be dot separated or the only element making up the local-part!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;, Assertion Error has occured:Expected error message: &#039;Double dot is not allowed before &#039;@&#039; symbol!&#039;, doesn&#039;t match the current one: &#039;Login failed. Please check User Name and password.&#039;]">
      <![CDATA[java.lang.Exception: Assertion Error has occured:  
[Assertion Error has occured:Expected error message: 'A '@' character must separate the local and domain parts!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Only one '@' symbol is allowed!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'None of the special characters in local part are allowed outside quotation marks!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Quoted strings must be dot separated or the only element making up the local-part!', doesn't match the current one: 'Login failed. Please check User Name and password.', Assertion Error has occured:Expected error message: 'Double dot is not allowed before '@' symbol!', doesn't match the current one: 'Login failed. Please check User Name and password.']
	at utils.AssertHandler.verifyNoAssertionFailed(AssertHandler.java:46)
	at galka.streletskaya.myProject.TestSuite.Test_01(TestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Test_01 -->
</testsuite> <!-- galka.streletskaya.myProject.TestSuite -->
